version: 0.0
os: linux

files:
  - source: docker-compose.yml
    destination: /home/ubuntu/crypto-bot
  - source: build.env
    destination: /home/ubuntu/crypto-bot
  - source: scripts
    destination: /home/ubuntu/crypto-bot/scripts

permissions:
  - object: /home/ubuntu/crypto-bot/scripts
    pattern: "**"
    mode: "755"
    type:
      - file

hooks:
  BeforeInstall:
    - location: scripts/stop.sh
      timeout: 30
      runas: ubuntu
  AfterInstall:
    - location: scripts/fetch_secrets.sh
      timeout: 30
      runas: ubuntu
    - location: scripts/start.sh
      timeout: 60
      runas: ubuntu
  ValidateService:
    - location: scripts/validate.sh
      timeout: 30
      runas: ubuntu
